### ISSUE TITLE
Sample usage on actual model and NoC simulator

### ISSUE THREAD

**Issue by raikonenfnu** [ucb-bar/cosa#5]
According to the paper, CoSA was tested on AlexNet, ResNet-50, ResNeXt-50 on the NoC simulator. Would be cool to see samples of it being used on these networks!

**Comment by hqjenny** [comment]
Hi, I'm working on releasing the NoC simulator this month. Will keep you posted!

**Comment by hqjenny** [comment]
The NoC simulation flow can be set up following the instructions under https://github.com/ucb-bar/cosa/tree/main/src/nocsim.
