### ISSUE TITLE
 Simba accelerator architecture.

### ISSUE THREAD

**Issue by FuyuWang** [ucb-bar/cosa#6]
Hi, the Simba accelerator architecture in the 'simba.yaml' of your source code is inconsistent with that in Table V. of your paper? 
Could you please explain this？Thanks!!!

**Comment by hqjenny** [comment]
Hi Fuyu, sorry for the late reply.  We have simba configurations of different sizes. I just pushed the simba_large.yaml we used for the paper at https://github.com/ucb-bar/cosa/blob/main/src/cosa/configs/arch/simba_large.yaml.
