### ISSUE TITLE
Empty output folder

### ISSUE THREAD

**Issue by zzczzc20** [ucb-bar/cosa#7]
Dear researchers,
After following your instructions in the readme file, I don't get any mapping yaml file. The output_dir folder has multi-level sub-folders. But there is no file inside these folders.
The program prints "INFO:gurobipy.gurobipy:Optimal solution found" and displays no error message.

**Comment by hqjenny** [comment]
@zzczzc20 Thanks for filing the issue. 

Sorry that we specified the import path of the utils.py file wrong when packaging the project. 
Now the issue should be fixed.  Please let me know if you still encounter any issues. 

To gain more info from the run, you can try removing this line: https://github.com/ucb-bar/cosa/blob/main/src/cosa/cosa.py#L16.

**Comment by hqjenny** [comment]
Also, please make sure to use the exact Timeloop commit [11920be](https://github.com/NVlabs/timeloop/commit/11920be5a744239c985ff049256f2fc40f65ce8b). 
There are changes in the current Timeloop we need to add support for.
