### ISSUE TITLE
Does CoSA verify numerical results with software?

### ISSUE THREAD

**Issue by Z-KN** [ucb-bar/cosa#9]
In the paper CoSA claims to have 8bit activations and weights. Are the quantization computation process and results on NoC cross-verified by software like PyTorch's quantization mode? I did not see nocsim do real computation but only count statistics. Am I correct?

**Comment by hqjenny** [comment]
Yes, the nocsim uses Timeloop cycles for its computation model. It constructs NoC packets using the traffic size but not the values. 

You can add an HLS C based PE implementation in nocsim and start putting real tensor values in the packet generation phase.

**Comment by Z-KN** [comment]
Thanks for the clarification!

**Comment by hqjenny** [comment]
Np. Please let me know if you have any other questions!
